# Generated by Django 4.1.5 on 2023-04-22 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_likepost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likepost',
            old_name='usernamme',
            new_name='username',
        ),
    ]
