# Generated by Django 4.1.5 on 2023-04-23 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_usernamme_likepost_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollwersCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.CharField(max_length=500)),
                ('user', models.CharField(max_length=100)),
            ],
        ),
    ]
